#' The harmonize_function merges the output data files from gps_function and gt3x_function by day and time (e.g., per minute),
#' keeping all rows from both files and displaying missing data for either accelerometer or GPS data as applicable.
#' This allows for straightforward editing or post-processing to eliminate undesired rows, producing a single CSV file with one row per minute that includes both latitude/longitude and activity classification.
#' @usage harmonize_function(acti_data, gps_data, participant_id = "P2E30001")
#' @param acti_data a csv file output generated by the gt3x_function with activity classification
#' @param gps_data a csv file output generated by the gps_function
#' @param participant_id a string of participant ID (default: "P2E30001")
#' @import tidyverse
#' @export
#' @returns This function saves a csv file with merged output from gps_function and gt3x_function by time.
#----------------------------------------------------------------------------------------------------------------#


#--------------------------------------------------harmonize_function--------------------------------------------#

harmonize_function = function(acti_data, gps_data, participant_id = "P2E30001") {

  acti_data = utils::read.csv(acti_data)
  gps_data = utils::read.csv(gps_data)

  #-----------------------------Data formatting----------------------------------#
  gps_data$`UTC TIME` = paste(gps_data$`UTC.DATE`, gps_data$`UTC.TIME`)
  gps_data$`UTC TIME` = ifelse(gps_data$`UTC TIME` == "NA NA", NA,
                               ifelse(gps_data$`UTC TIME` == "NA", NA, gps_data$`UTC TIME`))
  gps_data$`UTC TIME` = format(as.POSIXct(gps_data$`UTC TIME`), format = '%Y-%m-%d %H:%M')
  acti_data$time = format(as.POSIXct(acti_data$time), format = '%Y-%m-%d %H:%M')

  # Only keep time, activity counts and activity categories in activity dataset
  acti_data =
    acti_data %>%
    dplyr::select(time, AC, activity)

  new_data = dplyr::full_join(x = acti_data, y = gps_data, by = c("time" = "UTC TIME"))
  utils::write.csv(new_data, file = paste0(participant_id, "_merged.csv"))
}
